name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install dependencies
      run: mamba install pytest pytest-cov flake8

    - name: Install py2vega
      run: pip install -e .

    - name: Test flake8
      run: flake8 py2vega --ignore=E501,W504,W503

    - name: Run pytest
      run: pytest --cov-report term-missing --cov=py2vega.main test
